// Turkish tax offices data
export const turkishTaxOffices = [
  { name: "Adana Büyükşehir Belediyesi Vergi Dairesi", city: "Adana", district: "Merkez" },
  { name: "Adana Defterdarlığı", city: "Adana", district: "Merkez" },
  { name: "Adana Gümrük ve Ticaret Müdürlüğü", city: "Adana", district: "Merkez" },
  { name: "Adana Kurumlar Vergi Dairesi", city: "Adana", district: "Merkez" },
  { name: "Adana Maltepe Vergi Dairesi", city: "Adana", district: "Seyhan" },
  { name: "Adana Merkez Vergi Dairesi", city: "Adana", district: "Seyhan" },
  { name: "Adana Yüreğir Vergi Dairesi", city: "Adana", district: "Yüreğir" },
  { name: "Adıyaman Defterdarlığı", city: "Adıyaman", district: "Merkez" },
  { name: "Adıyaman Gümrük ve Ticaret Müdürlüğü", city: "Adıyaman", district: "Merkez" },
  { name: "Adıyaman Merkez Vergi Dairesi", city: "Adıyaman", district: "Merkez" },
  { name: "Afyonkarahisar Defterdarlığı", city: "Afyonkarahisar", district: "Merkez" },
  { name: "Afyonkarahisar Gümrük ve Ticaret Müdürlüğü", city: "Afyonkarahisar", district: "Merkez" },
  { name: "Afyonkarahisar Merkez Vergi Dairesi", city: "Afyonkarahisar", district: "Merkez" },
  { name: "Ağrı Defterdarlığı", city: "Ağrı", district: "Merkez" },
  { name: "Ağrı Gümrük ve Ticaret Müdürlüğü", city: "Ağrı", district: "Merkez" },
  { name: "Ağrı Merkez Vergi Dairesi", city: "Ağrı", district: "Merkez" },
  { name: "Amasya Defterdarlığı", city: "Amasya", district: "Merkez" },
  { name: "Amasya Gümrük ve Ticaret Müdürlüğü", city: "Amasya", district: "Merkez" },
  { name: "Amasya Merkez Vergi Dairesi", city: "Amasya", district: "Merkez" },
  { name: "Ankara Büyükşehir Belediyesi Vergi Dairesi", city: "Ankara", district: "Merkez" },
  { name: "Ankara Defterdarlığı", city: "Ankara", district: "Merkez" },
  { name: "Ankara Gümrük ve Ticaret Müdürlüğü", city: "Ankara", district: "Merkez" },
  { name: "Ankara Kurumlar Vergi Dairesi", city: "Ankara", district: "Merkez" },
  { name: "Ankara Maltepe Vergi Dairesi", city: "Ankara", district: "Yenimahalle" },
  { name: "Ankara Merkez Vergi Dairesi", city: "Ankara", district: "Çankaya" },
  { name: "Ankara Sincan Vergi Dairesi", city: "Ankara", district: "Sincan" },
  { name: "Ankara Yenimahalle Vergi Dairesi", city: "Ankara", district: "Yenimahalle" },
  { name: "Antalya Büyükşehir Belediyesi Vergi Dairesi", city: "Antalya", district: "Merkez" },
  { name: "Antalya Defterdarlığı", city: "Antalya", district: "Merkez" },
  { name: "Antalya Gümrük ve Ticaret Müdürlüğü", city: "Antalya", district: "Merkez" },
  { name: "Antalya Kurumlar Vergi Dairesi", city: "Antalya", district: "Merkez" },
  { name: "Antalya Merkez Vergi Dairesi", city: "Antalya", district: "Merkez" },
  { name: "Antalya Serik Vergi Dairesi", city: "Antalya", district: "Serik" },
  { name: "Artvin Defterdarlığı", city: "Artvin", district: "Merkez" },
  { name: "Artvin Gümrük ve Ticaret Müdürlüğü", city: "Artvin", district: "Merkez" },
  { name: "Artvin Merkez Vergi Dairesi", city: "Artvin", district: "Merkez" },
  { name: "Aydın Defterdarlığı", city: "Aydın", district: "Merkez" },
  { name: "Aydın Gümrük ve Ticaret Müdürlüğü", city: "Aydın", district: "Merkez" },
  { name: "Aydın Kurumlar Vergi Dairesi", city: "Aydın", district: "Merkez" },
  { name: "Aydın Merkez Vergi Dairesi", city: "Aydın", district: "Merkez" },
  { name: "Balıkesir Defterdarlığı", city: "Balıkesir", district: "Merkez" },
  { name: "Balıkesir Gümrük ve Ticaret Müdürlüğü", city: "Balıkesir", district: "Merkez" },
  { name: "Balıkesir Kurumlar Vergi Dairesi", city: "Balıkesir", district: "Merkez" },
  { name: "Balıkesir Merkez Vergi Dairesi", city: "Balıkesir", district: "Merkez" },
  { name: "Bilecik Defterdarlığı", city: "Bilecik", district: "Merkez" },
  { name: "Bilecik Gümrük ve Ticaret Müdürlüğü", city: "Bilecik", district: "Merkez" },
  { name: "Bilecik Merkez Vergi Dairesi", city: "Bilecik", district: "Merkez" },
  { name: "Bingöl Defterdarlığı", city: "Bingöl", district: "Merkez" },
  { name: "Bingöl Gümrük ve Ticaret Müdürlüğü", city: "Bingöl", district: "Merkez" },
  { name: "Bingöl Merkez Vergi Dairesi", city: "Bingöl", district: "Merkez" },
  { name: "Bitlis Defterdarlığı", city: "Bitlis", district: "Merkez" },
  { name: "Bitlis Gümrük ve Ticaret Müdürlüğü", city: "Bitlis", district: "Merkez" },
  { name: "Bitlis Merkez Vergi Dairesi", city: "Bitlis", district: "Merkez" },
  { name: "Bolu Defterdarlığı", city: "Bolu", district: "Merkez" },
  { name: "Bolu Gümrük ve Ticaret Müdürlüğü", city: "Bolu", district: "Merkez" },
  { name: "Bolu Merkez Vergi Dairesi", city: "Bolu", district: "Merkez" },
  { name: "Burdur Defterdarlığı", city: "Burdur", district: "Merkez" },
  { name: "Burdur Gümrük ve Ticaret Müdürlüğü", city: "Burdur", district: "Merkez" },
  { name: "Burdur Merkez Vergi Dairesi", city: "Burdur", district: "Merkez" },
  { name: "Bursa Büyükşehir Belediyesi Vergi Dairesi", city: "Bursa", district: "Merkez" },
  { name: "Bursa Defterdarlığı", city: "Bursa", district: "Merkez" },
  { name: "Bursa Gümrük ve Ticaret Müdürlüğü", city: "Bursa", district: "Merkez" },
  { name: "Bursa Kurumlar Vergi Dairesi", city: "Bursa", district: "Merkez" },
  { name: "Bursa Merkez Vergi Dairesi", city: "Bursa", district: "Osmangazi" },
  { name: "Bursa Yıldırım Vergi Dairesi", city: "Bursa", district: "Yıldırım" },
  { name: "Çanakkale Defterdarlığı", city: "Çanakkale", district: "Merkez" },
  { name: "Çanakkale Gümrük ve Ticaret Müdürlüğü", city: "Çanakkale", district: "Merkez" },
  { name: "Çanakkale Merkez Vergi Dairesi", city: "Çanakkale", district: "Merkez" },
  { name: "Çankırı Defterdarlığı", city: "Çankırı", district: "Merkez" },
  { name: "Çankırı Gümrük ve Ticaret Müdürlüğü", city: "Çankırı", district: "Merkez" },
  { name: "Çankırı Merkez Vergi Dairesi", city: "Çankırı", district: "Merkez" },
  { name: "Çorum Defterdarlığı", city: "Çorum", district: "Merkez" },
  { name: "Çorum Gümrük ve Ticaret Müdürlüğü", city: "Çorum", district: "Merkez" },
  { name: "Çorum Merkez Vergi Dairesi", city: "Çorum", district: "Merkez" },
  { name: "Denizli Defterdarlığı", city: "Denizli", district: "Merkez" },
  { name: "Denizli Gümrük ve Ticaret Müdürlüğü", city: "Denizli", district: "Merkez" },
  { name: "Denizli Kurumlar Vergi Dairesi", city: "Denizli", district: "Merkez" },
  { name: "Denizli Merkez Vergi Dairesi", city: "Denizli", district: "Merkez" },
  { name: "Diyarbakır Büyükşehir Belediyesi Vergi Dairesi", city: "Diyarbakır", district: "Merkez" },
  { name: "Diyarbakır Defterdarlığı", city: "Diyarbakır", district: "Merkez" },
  { name: "Diyarbakır Gümrük ve Ticaret Müdürlüğü", city: "Diyarbakır", district: "Merkez" },
  { name: "Diyarbakır Kurumlar Vergi Dairesi", city: "Diyarbakır", district: "Merkez" },
  { name: "Diyarbakır Merkez Vergi Dairesi", city: "Diyarbakır", district: "Bağlar" },
  { name: "Edirne Defterdarlığı", city: "Edirne", district: "Merkez" },
  { name: "Edirne Gümrük ve Ticaret Müdürlüğü", city: "Edirne", district: "Merkez" },
  { name: "Edirne Merkez Vergi Dairesi", city: "Edirne", district: "Merkez" },
  { name: "Elazığ Defterdarlığı", city: "Elazığ", district: "Merkez" },
  { name: "Elazığ Gümrük ve Ticaret Müdürlüğü", city: "Elazığ", district: "Merkez" },
  { name: "Elazığ Merkez Vergi Dairesi", city: "Elazığ", district: "Merkez" },
  { name: "Erzincan Defterdarlığı", city: "Erzincan", district: "Merkez" },
  { name: "Erzincan Gümrük ve Ticaret Müdürlüğü", city: "Erzincan", district: "Merkez" },
  { name: "Erzincan Merkez Vergi Dairesi", city: "Erzincan", district: "Merkez" },
  { name: "Erzurum Defterdarlığı", city: "Erzurum", district: "Merkez" },
  { name: "Erzurum Gümrük ve Ticaret Müdürlüğü", city: "Erzurum", district: "Merkez" },
  { name: "Erzurum Kurumlar Vergi Dairesi", city: "Erzurum", district: "Merkez" },
  { name: "Erzurum Merkez Vergi Dairesi", city: "Erzurum", district: "Merkez" },
  { name: "Eskişehir Defterdarlığı", city: "Eskişehir", district: "Merkez" },
  { name: "Eskişehir Gümrük ve Ticaret Müdürlüğü", city: "Eskişehir", district: "Merkez" },
  { name: "Eskişehir Kurumlar Vergi Dairesi", city: "Eskişehir", district: "Merkez" },
  { name: "Eskişehir Merkez Vergi Dairesi", city: "Eskişehir", district: "Merkez" },
  { name: "Gaziantep Büyükşehir Belediyesi Vergi Dairesi", city: "Gaziantep", district: "Merkez" },
  { name: "Gaziantep Defterdarlığı", city: "Gaziantep", district: "Merkez" },
  { name: "Gaziantep Gümrük ve Ticaret Müdürlüğü", city: "Gaziantep", district: "Merkez" },
  { name: "Gaziantep Kurumlar Vergi Dairesi", city: "Gaziantep", district: "Merkez" },
  { name: "Gaziantep Merkez Vergi Dairesi", city: "Gaziantep", district: "Şehitkamil" },
  { name: "Giresun Defterdarlığı", city: "Giresun", district: "Merkez" },
  { name: "Giresun Gümrük ve Ticaret Müdürlüğü", city: "Giresun", district: "Merkez" },
  { name: "Giresun Merkez Vergi Dairesi", city: "Giresun", district: "Merkez" },
  { name: "Gümüşhane Defterdarlığı", city: "Gümüşhane", district: "Merkez" },
  { name: "Gümüşhane Gümrük ve Ticaret Müdürlüğü", city: "Gümüşhane", district: "Merkez" },
  { name: "Gümüşhane Merkez Vergi Dairesi", city: "Gümüşhane", district: "Merkez" },
  { name: "Hakkari Defterdarlığı", city: "Hakkari", district: "Merkez" },
  { name: "Hakkari Gümrük ve Ticaret Müdürlüğü", city: "Hakkari", district: "Merkez" },
  { name: "Hakkari Merkez Vergi Dairesi", city: "Hakkari", district: "Merkez" },
  { name: "Hatay Defterdarlığı", city: "Hatay", district: "Merkez" },
  { name: "Hatay Gümrük ve Ticaret Müdürlüğü", city: "Hatay", district: "Merkez" },
  { name: "Hatay Kurumlar Vergi Dairesi", city: "Hatay", district: "Merkez" },
  { name: "Hatay Merkez Vergi Dairesi", city: "Hatay", district: "Antakya" },
  { name: "Isparta Defterdarlığı", city: "Isparta", district: "Merkez" },
  { name: "Isparta Gümrük ve Ticaret Müdürlüğü", city: "Isparta", district: "Merkez" },
  { name: "Isparta Merkez Vergi Dairesi", city: "Isparta", district: "Merkez" },
  { name: "Mersin Büyükşehir Belediyesi Vergi Dairesi", city: "Mersin", district: "Merkez" },
  { name: "Mersin Defterdarlığı", city: "Mersin", district: "Merkez" },
  { name: "Mersin Gümrük ve Ticaret Müdürlüğü", city: "Mersin", district: "Merkez" },
  { name: "Mersin Kurumlar Vergi Dairesi", city: "Mersin", district: "Merkez" },
  { name: "Mersin Merkez Vergi Dairesi", city: "Mersin", district: "Tarsus" },
  { name: "İstanbul Arnavutköy Vergi Dairesi", city: "İstanbul", district: "Arnavutköy" },
  { name: "İstanbul Ataşehir Vergi Dairesi", city: "İstanbul", district: "Ataşehir" },
  { name: "İstanbul Avcılar Vergi Dairesi", city: "İstanbul", district: "Avcılar" },
  { name: "İstanbul Bağcılar Vergi Dairesi", city: "İstanbul", district: "Bağcılar" },
  { name: "İstanbul Bahçelievler Vergi Dairesi", city: "İstanbul", district: "Bahçelievler" },
  { name: "İstanbul Bakırköy Vergi Dairesi", city: "İstanbul", district: "Bakırköy" },
  { name: "İstanbul Başakşehir Vergi Dairesi", city: "İstanbul", district: "Başakşehir" },
  { name: "İstanbul Bayrampaşa Vergi Dairesi", city: "İstanbul", district: "Bayrampaşa" },
  { name: "İstanbul Beşiktaş Vergi Dairesi", city: "İstanbul", district: "Beşiktaş" },
  { name: "İstanbul Beykoz Vergi Dairesi", city: "İstanbul", district: "Beykoz" },
  { name: "İstanbul Beylikdüzü Vergi Dairesi", city: "İstanbul", district: "Beylikdüzü" },
  { name: "İstanbul Beyoğlu Vergi Dairesi", city: "İstanbul", district: "Beyoğlu" },
  { name: "İstanbul Büyükçekmece Vergi Dairesi", city: "İstanbul", district: "Büyükçekmece" },
  { name: "İstanbul Çatalca Vergi Dairesi", city: "İstanbul", district: "Çatalca" },
  { name: "İstanbul Çekmeköy Vergi Dairesi", city: "İstanbul", district: "Çekmeköy" },
  { name: "İstanbul Esenler Vergi Dairesi", city: "İstanbul", district: "Esenler" },
  { name: "İstanbul Esenyurt Vergi Dairesi", city: "İstanbul", district: "Esenyurt" },
  { name: "İstanbul Fatih Vergi Dairesi", city: "İstanbul", district: "Fatih" },
  { name: "İstanbul Güngören Vergi Dairesi", city: "İstanbul", district: "Güngören" },
  { name: "İstanbul Kadıköy Vergi Dairesi", city: "İstanbul", district: "Kadıköy" },
  { name: "İstanbul Kağıthane Vergi Dairesi", city: "İstanbul", district: "Kağıthane" },
  { name: "İstanbul Kartal Vergi Dairesi", city: "İstanbul", district: "Kartal" },
  { name: "İstanbul Kurumlar Vergi Dairesi", city: "İstanbul", district: "Merkez" },
  { name: "İstanbul Küçükçekmece Vergi Dairesi", city: "İstanbul", district: "Küçükçekmece" },
  { name: "İstanbul Maltepe Vergi Dairesi", city: "İstanbul", district: "Maltepe" },
  { name: "İstanbul Merkez Vergi Dairesi", city: "İstanbul", district: "Fatih" },
  { name: "İstanbul Pendik Vergi Dairesi", city: "İstanbul", district: "Pendik" },
  { name: "İstanbul Sancaktepe Vergi Dairesi", city: "İstanbul", district: "Sancaktepe" },
  { name: "İstanbul Sarıyer Vergi Dairesi", city: "İstanbul", district: "Sarıyer" },
  { name: "İstanbul Silivri Vergi Dairesi", city: "İstanbul", district: "Silivri" },
  { name: "İstanbul Sultanbeyli Vergi Dairesi", city: "İstanbul", district: "Sultanbeyli" },
  { name: "İstanbul Sultangazi Vergi Dairesi", city: "İstanbul", district: "Sultangazi" },
  { name: "İstanbul Şile Vergi Dairesi", city: "İstanbul", district: "Şile" },
  { name: "İstanbul Şişli Vergi Dairesi", city: "İstanbul", district: "Şişli" },
  { name: "İstanbul Tuzla Vergi Dairesi", city: "İstanbul", district: "Tuzla" },
  { name: "İstanbul Ümraniye Vergi Dairesi", city: "İstanbul", district: "Ümraniye" },
  { name: "İstanbul Üsküdar Vergi Dairesi", city: "İstanbul", district: "Üsküdar" },
  { name: "İstanbul Zeytinburnu Vergi Dairesi", city: "İstanbul", district: "Zeytinburnu" },
  { name: "İzmir Büyükşehir Belediyesi Vergi Dairesi", city: "İzmir", district: "Merkez" },
  { name: "İzmir Bornova Vergi Dairesi", city: "İzmir", district: "Bornova" },
  { name: "İzmir Defterdarlığı", city: "İzmir", district: "Merkez" },
  { name: "İzmir Gümrük ve Ticaret Müdürlüğü", city: "İzmir", district: "Merkez" },
  { name: "İzmir Karşıyaka Vergi Dairesi", city: "İzmir", district: "Karşıyaka" },
  { name: "İzmir Konak Vergi Dairesi", city: "İzmir", district: "Konak" },
  { name: "İzmir Kurumlar Vergi Dairesi", city: "İzmir", district: "Merkez" },
  { name: "İzmir Merkez Vergi Dairesi", city: "İzmir", district: "Konak" },
  { name: "Kahramanmaraş Defterdarlığı", city: "Kahramanmaraş", district: "Merkez" },
  { name: "Kahramanmaraş Gümrük ve Ticaret Müdürlüğü", city: "Kahramanmaraş", district: "Merkez" },
  { name: "Kahramanmaraş Kurumlar Vergi Dairesi", city: "Kahramanmaraş", district: "Merkez" },
  { name: "Kahramanmaraş Merkez Vergi Dairesi", city: "Kahramanmaraş", district: "Merkez" },
  { name: "Karabük Defterdarlığı", city: "Karabük", district: "Merkez" },
  { name: "Karabük Gümrük ve Ticaret Müdürlüğü", city: "Karabük", district: "Merkez" },
  { name: "Karabük Merkez Vergi Dairesi", city: "Karabük", district: "Merkez" },
  { name: "Karaman Defterdarlığı", city: "Karaman", district: "Merkez" },
  { name: "Karaman Gümrük ve Ticaret Müdürlüğü", city: "Karaman", district: "Merkez" },
  { name: "Karaman Merkez Vergi Dairesi", city: "Karaman", district: "Merkez" },
  { name: "Kars Defterdarlığı", city: "Kars", district: "Merkez" },
  { name: "Kars Gümrük ve Ticaret Müdürlüğü", city: "Kars", district: "Merkez" },
  { name: "Kars Merkez Vergi Dairesi", city: "Kars", district: "Merkez" },
  { name: "Kastamonu Defterdarlığı", city: "Kastamonu", district: "Merkez" },
  { name: "Kastamonu Gümrük ve Ticaret Müdürlüğü", city: "Kastamonu", district: "Merkez" },
  { name: "Kastamonu Merkez Vergi Dairesi", city: "Kastamonu", district: "Merkez" },
  { name: "Kayseri Büyükşehir Belediyesi Vergi Dairesi", city: "Kayseri", district: "Merkez" },
  { name: "Kayseri Defterdarlığı", city: "Kayseri", district: "Merkez" },
  { name: "Kayseri Gümrük ve Ticaret Müdürlüğü", city: "Kayseri", district: "Merkez" },
  { name: "Kayseri Kurumlar Vergi Dairesi", city: "Kayseri", district: "Merkez" },
  { name: "Kayseri Merkez Vergi Dairesi", city: "Kayseri", district: "Merkez" },
  { name: "Kırıkkale Defterdarlığı", city: "Kırıkkale", district: "Merkez" },
  { name: "Kırıkkale Gümrük ve Ticaret Müdürlüğü", city: "Kırıkkale", district: "Merkez" },
  { name: "Kırıkkale Merkez Vergi Dairesi", city: "Kırıkkale", district: "Merkez" },
  { name: "Kırklareli Defterdarlığı", city: "Kırklareli", district: "Merkez" },
  { name: "Kırklareli Gümrük ve Ticaret Müdürlüğü", city: "Kırklareli", district: "Merkez" },
  { name: "Kırklareli Merkez Vergi Dairesi", city: "Kırklareli", district: "Merkez" },
  { name: "Kırşehir Defterdarlığı", city: "Kırşehir", district: "Merkez" },
  { name: "Kırşehir Gümrük ve Ticaret Müdürlüğü", city: "Kırşehir", district: "Merkez" },
  { name: "Kırşehir Merkez Vergi Dairesi", city: "Kırşehir", district: "Merkez" },
  { name: "Kilis Defterdarlığı", city: "Kilis", district: "Merkez" },
  { name: "Kilis Gümrük ve Ticaret Müdürlüğü", city: "Kilis", district: "Merkez" },
  { name: "Kilis Merkez Vergi Dairesi", city: "Kilis", district: "Merkez" },
  { name: "Kocaeli Büyükşehir Belediyesi Vergi Dairesi", city: "Kocaeli", district: "Merkez" },
  { name: "Kocaeli Defterdarlığı", city: "Kocaeli", district: "Merkez" },
  { name: "Kocaeli Gölcük Vergi Dairesi", city: "Kocaeli", district: "Gölcük" },
  { name: "Kocaeli Gümrük ve Ticaret Müdürlüğü", city: "Kocaeli", district: "Merkez" },
  { name: "Kocaeli İzmit Vergi Dairesi", city: "Kocaeli", district: "İzmit" },
  { name: "Kocaeli Kurumlar Vergi Dairesi", city: "Kocaeli", district: "Merkez" },
  { name: "Kocaeli Merkez Vergi Dairesi", city: "Kocaeli", district: "İzmit" },
  { name: "Konya Büyükşehir Belediyesi Vergi Dairesi", city: "Konya", district: "Merkez" },
  { name: "Konya Defterdarlığı", city: "Konya", district: "Merkez" },
  { name: "Konya Gümrük ve Ticaret Müdürlüğü", city: "Konya", district: "Merkez" },
  { name: "Konya Kurumlar Vergi Dairesi", city: "Konya", district: "Merkez" },
  { name: "Konya Merkez Vergi Dairesi", city: "Konya", district: "Meram" },
  { name: "Kütahya Defterdarlığı", city: "Kütahya", district: "Merkez" },
  { name: "Kütahya Gümrük ve Ticaret Müdürlüğü", city: "Kütahya", district: "Merkez" },
  { name: "Kütahya Merkez Vergi Dairesi", city: "Kütahya", district: "Merkez" },
  { name: "Malatya Defterdarlığı", city: "Malatya", district: "Merkez" },
  { name: "Malatya Gümrük ve Ticaret Müdürlüğü", city: "Malatya", district: "Merkez" },
  { name: "Malatya Kurumlar Vergi Dairesi", city: "Malatya", district: "Merkez" },
  { name: "Malatya Merkez Vergi Dairesi", city: "Malatya", district: "Merkez" },
  { name: "Manisa Defterdarlığı", city: "Manisa", district: "Merkez" },
  { name: "Manisa Gümrük ve Ticaret Müdürlüğü", city: "Manisa", district: "Merkez" },
  { name: "Manisa Kurumlar Vergi Dairesi", city: "Manisa", district: "Merkez" },
  { name: "Manisa Merkez Vergi Dairesi", city: "Manisa", district: "Merkez" },
  { name: "Mardin Defterdarlığı", city: "Mardin", district: "Merkez" },
  { name: "Mardin Gümrük ve Ticaret Müdürlüğü", city: "Mardin", district: "Merkez" },
  { name: "Mardin Merkez Vergi Dairesi", city: "Mardin", district: "Merkez" },
  { name: "Muğla Defterdarlığı", city: "Muğla", district: "Merkez" },
  { name: "Muğla Gümrük ve Ticaret Müdürlüğü", city: "Muğla", district: "Merkez" },
  { name: "Muğla Kurumlar Vergi Dairesi", city: "Muğla", district: "Merkez" },
  { name: "Muğla Merkez Vergi Dairesi", city: "Muğla", district: "Merkez" },
  { name: "Muş Defterdarlığı", city: "Muş", district: "Merkez" },
  { name: "Muş Gümrük ve Ticaret Müdürlüğü", city: "Muş", district: "Merkez" },
  { name: "Muş Merkez Vergi Dairesi", city: "Muş", district: "Merkez" },
  { name: "Nevşehir Defterdarlığı", city: "Nevşehir", district: "Merkez" },
  { name: "Nevşehir Gümrük ve Ticaret Müdürlüğü", city: "Nevşehir", district: "Merkez" },
  { name: "Nevşehir Merkez Vergi Dairesi", city: "Nevşehir", district: "Merkez" },
  { name: "Niğde Defterdarlığı", city: "Niğde", district: "Merkez" },
  { name: "Niğde Gümrük ve Ticaret Müdürlüğü", city: "Niğde", district: "Merkez" },
  { name: "Niğde Merkez Vergi Dairesi", city: "Niğde", district: "Merkez" },
  { name: "Ordu Defterdarlığı", city: "Ordu", district: "Merkez" },
  { name: "Ordu Gümrük ve Ticaret Müdürlüğü", city: "Ordu", district: "Merkez" },
  { name: "Ordu Merkez Vergi Dairesi", city: "Ordu", district: "Merkez" },
  { name: "Osmaniye Defterdarlığı", city: "Osmaniye", district: "Merkez" },
  { name: "Osmaniye Gümrük ve Ticaret Müdürlüğü", city: "Osmaniye", district: "Merkez" },
  { name: "Osmaniye Merkez Vergi Dairesi", city: "Osmaniye", district: "Merkez" },
  { name: "Rize Defterdarlığı", city: "Rize", district: "Merkez" },
  { name: "Rize Gümrük ve Ticaret Müdürlüğü", city: "Rize", district: "Merkez" },
  { name: "Rize Merkez Vergi Dairesi", city: "Rize", district: "Merkez" },
  { name: "Sakarya Defterdarlığı", city: "Sakarya", district: "Merkez" },
  { name: "Sakarya Gümrük ve Ticaret Müdürlüğü", city: "Sakarya", district: "Merkez" },
  { name: "Sakarya Kurumlar Vergi Dairesi", city: "Sakarya", district: "Merkez" },
  { name: "Sakarya Merkez Vergi Dairesi", city: "Sakarya", district: "Merkez" },
  { name: "Samsun Defterdarlığı", city: "Samsun", district: "Merkez" },
  { name: "Samsun Gümrük ve Ticaret Müdürlüğü", city: "Samsun", district: "Merkez" },
  { name: "Samsun Kurumlar Vergi Dairesi", city: "Samsun", district: "Merkez" },
  { name: "Samsun Merkez Vergi Dairesi", city: "Samsun", district: "İlkadım" },
  { name: "Siirt Defterdarlığı", city: "Siirt", district: "Merkez" },
  { name: "Siirt Gümrük ve Ticaret Müdürlüğü", city: "Siirt", district: "Merkez" },
  { name: "Siirt Merkez Vergi Dairesi", city: "Siirt", district: "Merkez" },
  { name: "Sinop Defterdarlığı", city: "Sinop", district: "Merkez" },
  { name: "Sinop Gümrük ve Ticaret Müdürlüğü", city: "Sinop", district: "Merkez" },
  { name: "Sinop Merkez Vergi Dairesi", city: "Sinop", district: "Merkez" },
  { name: "Sivas Defterdarlığı", city: "Sivas", district: "Merkez" },
  { name: "Sivas Gümrük ve Ticaret Müdürlüğü", city: "Sivas", district: "Merkez" },
  { name: "Sivas Merkez Vergi Dairesi", city: "Sivas", district: "Merkez" },
  { name: "Şanlıurfa Defterdarlığı", city: "Şanlıurfa", district: "Merkez" },
  { name: "Şanlıurfa Gümrük ve Ticaret Müdürlüğü", city: "Şanlıurfa", district: "Merkez" },
  { name: "Şanlıurfa Kurumlar Vergi Dairesi", city: "Şanlıurfa", district: "Merkez" },
  { name: "Şanlıurfa Merkez Vergi Dairesi", city: "Şanlıurfa", district: "Merkez" },
  { name: "Şırnak Defterdarlığı", city: "Şırnak", district: "Merkez" },
  { name: "Şırnak Gümrük ve Ticaret Müdürlüğü", city: "Şırnak", district: "Merkez" },
  { name: "Şırnak Merkez Vergi Dairesi", city: "Şırnak", district: "Merkez" },
  { name: "Tekirdağ Defterdarlığı", city: "Tekirdağ", district: "Merkez" },
  { name: "Tekirdağ Gümrük ve Ticaret Müdürlüğü", city: "Tekirdağ", district: "Merkez" },
  { name: "Tekirdağ Kurumlar Vergi Dairesi", city: "Tekirdağ", district: "Merkez" },
  { name: "Tekirdağ Merkez Vergi Dairesi", city: "Tekirdağ", district: "Süleymanpaşa" },
  { name: "Tokat Defterdarlığı", city: "Tokat", district: "Merkez" },
  { name: "Tokat Gümrük ve Ticaret Müdürlüğü", city: "Tokat", district: "Merkez" },
  { name: "Tokat Merkez Vergi Dairesi", city: "Tokat", district: "Merkez" },
  { name: "Trabzon Defterdarlığı", city: "Trabzon", district: "Merkez" },
  { name: "Trabzon Gümrük ve Ticaret Müdürlüğü", city: "Trabzon", district: "Merkez" },
  { name: "Trabzon Kurumlar Vergi Dairesi", city: "Trabzon", district: "Merkez" },
  { name: "Trabzon Merkez Vergi Dairesi", city: "Trabzon", district: "Ortahisar" },
  { name: "Tunceli Defterdarlığı", city: "Tunceli", district: "Merkez" },
  { name: "Tunceli Gümrük ve Ticaret Müdürlüğü", city: "Tunceli", district: "Merkez" },
  { name: "Tunceli Merkez Vergi Dairesi", city: "Tunceli", district: "Merkez" },
  { name: "Uşak Defterdarlığı", city: "Uşak", district: "Merkez" },
  { name: "Uşak Gümrük ve Ticaret Müdürlüğü", city: "Uşak", district: "Merkez" },
  { name: "Uşak Merkez Vergi Dairesi", city: "Uşak", district: "Merkez" },
  { name: "Van Defterdarlığı", city: "Van", district: "Merkez" },
  { name: "Van Gümrük ve Ticaret Müdürlüğü", city: "Van", district: "Merkez" },
  { name: "Van Kurumlar Vergi Dairesi", city: "Van", district: "Merkez" },
  { name: "Van Merkez Vergi Dairesi", city: "Van", district: "İpekyolu" },
  { name: "Yalova Defterdarlığı", city: "Yalova", district: "Merkez" },
  { name: "Yalova Gümrük ve Ticaret Müdürlüğü", city: "Yalova", district: "Merkez" },
  { name: "Yalova Merkez Vergi Dairesi", city: "Yalova", district: "Merkez" },
  { name: "Yozgat Defterdarlığı", city: "Yozgat", district: "Merkez" },
  { name: "Yozgat Gümrük ve Ticaret Müdürlüğü", city: "Yozgat", district: "Merkez" },
  { name: "Yozgat Merkez Vergi Dairesi", city: "Yozgat", district: "Merkez" },
  { name: "Zonguldak Defterdarlığı", city: "Zonguldak", district: "Merkez" },
  { name: "Zonguldak Gümrük ve Ticaret Müdürlüğü", city: "Zonguldak", district: "Merkez" },
  { name: "Zonguldak Merkez Vergi Dairesi", city: "Zonguldak", district: "Merkez" }
];